name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm install sqlite3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
          uses: cypress-io/github-action@v1
          with:
            record: true
            start: npm run test:start
            wait-on: 'http://localhost:3000'
          env:
            # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.cypress_token }}
            GITHUB_TOKEN: ${{ secrets.gh_token }}
